apiVersion: v1
kind: Service
metadata: 
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector: 
    project: expense
    component: mysql
    tier: db
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata: 
  name: mysql
  namespace: expense
spec:
  type: LoadBalancer
  selector: 
    project: expense
    component: mysql
    tier: db
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
